/* MeditasiKu V17 — clean modular UI. No React bundle, Base64 artwork, SVG icons,
   legacy renderer, or DOM-patching layer. */
(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const app=$('#app'),KEY='meditasiku.shell.v17',repo=window.MEDITASIKU_CATALOGUE;
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
const write=patch=>{state={...state,...patch};localStorage.setItem(KEY,JSON.stringify(state))};
let state={route:'splash',onboardingDone:false,onboardingStep:0,exploreQuery:'',exploreCategory:'',exploreLimit:24,...read()};
let renderToken=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=v=>String(v??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const icon=(name,label='')=>`<img class="icon" src="./assets/icons/ui/${name}.png" alt="${esc(label)}" onerror="this.hidden=true">`;
const artwork=d=>d?.artwork||'./assets/app/dose-detail-background.webp';
const cover=c=>`./assets/categories-raster/category-${slug(c.id)}.webp`;
const all=()=>repo?.getAll?.()||[];
const cats=()=>repo?.getCategories?.()||[];
const store=name=>{try{const result=window.MeditasiKu?.storage?.all?.(name);return result?.catch?.(()=>[])||Promise.resolve([])}catch{return Promise.resolve([])}};
function toast(message){const n=$('#toast');n.textContent=message;n.classList.add('show');clearTimeout(n.t);n.t=setTimeout(()=>n.classList.remove('show'),2600)}
function route(name,patch={}){write({route:name,...patch});scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});render()}
function image(src,alt,cls=''){return `<img class="${cls}" src="${esc(src)}" alt="${esc(alt)}" loading="lazy" decoding="async" onerror="this.src='./assets/app/sanctuary-gateway.webp'">`}
function nav(){return `<nav class="dock" aria-label="Navigasi utama">${[['home','home','Beranda'],['explore','explore','Explore'],['create','create','Create'],['library','library','Library'],['profile','profile','Profil']].map(([r,i,l])=>`<button type="button" data-route="${r}" class="${state.route===r?'active':''} ${r==='create'?'create':''}" aria-label="${l}">${icon(i)}<span>${l}</span></button>`).join('')}</nav>`}
function bindNav(){$$('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route))}
function page(inner,screen){app.dataset.screen=screen;app.innerHTML=`<main class="screen screen-${screen}">${inner}</main>${nav()}`;bindNav();bindCommon()}
function bindCommon(){$$('[data-dose]').forEach(b=>b.onclick=()=>{const d=repo.getById(b.dataset.dose);if(d)window.MeditasiKu.detail(d)});$$('[data-player]').forEach(b=>b.onclick=()=>{const d=repo.getById(b.dataset.player);if(d)window.MeditasiKu.player(d)});$$('[data-category]').forEach(b=>b.onclick=()=>window.MeditasiKu.categories(b.dataset.category));$$('[data-all-categories]').forEach(b=>b.onclick=()=>window.MeditasiKu.categories());$$('[data-action="search"]').forEach(b=>b.onclick=()=>route('explore',{focusSearch:true}))}
function splash(){app.dataset.screen='splash';app.innerHTML=`<main class="gate"><div class="gate-glow"></div><section><img class="brand" src="./assets/brand/meditasiku-logo-mark.png" alt="Logo MeditasiKu"><p class="eyebrow">Di Ambang Sunyi</p><h1>MeditasiKu</h1><p class="gate-copy">Temukan semesta di dalam diri melalui perjalanan suara yang dibuat untuk satu tujuan yang jelas.</p><div class="gate-facts"><span><b>500</b>Dose</span><span><b>50</b>Kategori</span><span><b>Nyata</b>DSP Lokal</span></div><button class="primary enter">Masuki Sanctuary</button></section></main>`;$('.enter').onclick=()=>state.onboardingDone?route('home'):route('onboarding',{onboardingStep:0})}
const onboarding=[
 {art:'onboarding-01-welcome.webp',k:'Gerbang pertama',t:'Selamat Datang di MeditasiKu',p:'Ruang dengar personal untuk beristirahat, fokus, bermeditasi, dan menjelajahi suasana tanpa janji medis.'},
 {art:'onboarding-02-goals.webp',k:'Tujuan Anda',t:'Apa yang ingin Anda rasakan?',p:'Pilih tujuan utama agar Home dan rekomendasi pertama lebih relevan.',choices:['Tidur','Relaksasi','Fokus','Meditasi','Belajar','Mimpi']},
 {art:'onboarding-03-sounds.webp',k:'Karakter suara',t:'Suasana yang terasa nyaman',p:'Pilihan ini membantu menyusun ambience. Setiap Dose tetap membatasi tema berdasarkan kecocokan recipe.',choices:['Hujan','Pantai','Hutan','Angin','Api Unggun','Malam']},
 {art:'onboarding-06-safety.webp',k:'Dengarkan dengan aman',t:'Volume nyaman lebih penting',p:'Jangan gunakan saat mengemudi atau mengoperasikan mesin. Hentikan sesi jika merasa pusing atau tidak nyaman.',safety:true}
];
function onboardingScreen(){const i=Math.max(0,Math.min(onboarding.length-1,state.onboardingStep||0)),s=onboarding[i],prefs=state.preferences||{goals:[],sounds:[]},key=i===1?'goals':'sounds';app.dataset.screen='onboarding';app.innerHTML=`<main class="onboarding" style="--onboarding:url('./assets/app/${s.art}')"><div class="onboarding-shade"></div><section><div class="steps">${onboarding.map((_,n)=>`<i class="${n<=i?'on':''}"></i>`).join('')}</div><p class="eyebrow">${s.k}</p><h1>${s.t}</h1><p>${s.p}</p>${s.choices?`<div class="choices">${s.choices.map(x=>`<button aria-pressed="${(prefs[key]||[]).includes(x)}" data-choice="${x}">${x}</button>`).join('')}</div>`:''}${s.safety?'<label class="safety"><input type="checkbox" id="safe"> Saya memahami panduan keselamatan.</label>':''}<div class="onboarding-actions">${i?'<button class="secondary back">Kembali</button>':''}<button class="primary next">${i===onboarding.length-1?'Mulai Perjalanan':'Lanjut'}</button></div></section></main>`;$$('[data-choice]').forEach(b=>b.onclick=()=>{const p=state.preferences||{goals:[],sounds:[]},arr=[...(p[key]||[])],x=b.dataset.choice,at=arr.indexOf(x);at>=0?arr.splice(at,1):arr.push(x);write({preferences:{...p,[key]:arr}});b.setAttribute('aria-pressed',String(at<0))});$('.back')?.addEventListener('click',()=>route('onboarding',{onboardingStep:i-1}));$('.next').onclick=()=>{if(s.choices&&!(state.preferences?.[key]||[]).length)return toast('Pilih minimal satu opsi.');if(s.safety&&!$('#safe').checked)return toast('Centang panduan keselamatan terlebih dahulu.');if(i<onboarding.length-1)route('onboarding',{onboardingStep:i+1});else route('home',{onboardingDone:true,onboardingStep:0})}}
function doseCard(d,wide=false){return `<button class="dose-card ${wide?'wide':''}" data-dose="${d.id}">${image(artwork(d),`Artwork ${d.title}`)}<span><small>${esc(d.categoryLabel||d.cat)} · ${d.duration} menit</small><strong>${esc(d.title)}</strong><em>${esc(d.shortDescription)}</em></span>${icon('chevron-right')}</button>`}
async function home(){const token=++renderToken,[hist,fav]=await Promise.all([store('history'),store('favorites')]);if(token!==renderToken)return;const latest=hist.sort((a,b)=>(b.at||0)-(a.at||0))[0],hero=repo.getById(latest?.doseId||latest?.canonicalId)||all()[0],prefs=state.preferences||{},terms=[...(prefs.goals||[]),...(prefs.sounds||[])].map(x=>x.toLowerCase()),ranked=all().map(d=>({d,n:terms.reduce((n,t)=>n+([d.title,d.categoryLabel,d.shortDescription,d.howItSounds].join(' ').toLowerCase().includes(t)?1:0),0)})).sort((a,b)=>b.n-a.n).slice(0,6).map(x=>x.d);page(`<header class="home-head"><div><p class="eyebrow">The Sanctuary</p><h1>${greeting()}, Sahabat</h1></div><button class="icon-button" data-action="search" aria-label="Cari Dose">${icon('search')}</button></header><section class="home-hero">${image(artwork(hero),`Artwork ${hero.title}`)}<div><p class="eyebrow">${latest?'Lanjutkan perjalanan':'Ritual pertama Anda'}</p><h2>${esc(hero.title)}</h2><p>${esc(hero.shortDescription)}</p><button class="play" data-player="${hero.id}" aria-label="Putar ${esc(hero.title)}">${icon('play')}</button></div></section><section class="ritual"><p class="eyebrow">Disusun dari pilihan Anda</p><h2>Sanctuary Personal</h2><p>${esc([...(prefs.goals||[]),...(prefs.sounds||[])].join(' · ')||'Pilih perjalanan berdasarkan kebutuhan hari ini.')}</p><div class="journey-rail">${ranked.slice(0,3).map(d=>doseCard(d)).join('')}</div></section><section class="home-path"><div><p class="eyebrow">Jelajahi lebih jauh</p><h2>Temukan ruang berikutnya</h2></div><button class="secondary" data-route="explore">Buka Explore</button></section>`, 'home')}
function greeting(){const h=new Date().getHours();return h<11?'Selamat Pagi':h<15?'Selamat Siang':h<19?'Selamat Sore':'Selamat Malam'}
function explore(){const q=(state.exploreQuery||'').toLowerCase(),cat=state.exploreCategory||'',limit=state.exploreLimit||24;let data=all().filter(d=>(!cat||d.cat===cat||d.categoryId===cat)&&(!q||[d.title,d.categoryLabel,d.shortDescription,d.listeningOutcome,d.howItSounds].join(' ').toLowerCase().includes(q)));page(`<header class="page-head"><div><p class="eyebrow">Peta Perjalanan</p><h1>Explore</h1><p>Temukan Dose dari fungsi, karakter suara, atau suasana yang Anda butuhkan.</p></div>${icon('explore')}</header><section class="search-panel"><label>${icon('search')}<input id="explore-search" value="${esc(state.exploreQuery||'')}" placeholder="Cari judul, fungsi, atau suasana"></label><select id="explore-category"><option value="">Semua 50 kategori</option>${cats().map(c=>`<option value="${c.id}" ${cat===c.id?'selected':''}>${esc(c.label)} · ${c.count}</option>`).join('')}</select></section><section class="category-rail" aria-label="Kategori pilihan">${cats().slice(0,12).map(c=>`<button data-category="${c.id}" style="--cover:url('${cover(c)}')"><span><strong>${esc(c.label)}</strong><small>${c.count} Dose</small></span></button>`).join('')}<button class="all-categories" data-all-categories><span><strong>Semua Kategori</strong><small>50 ruang</small></span></button></section><div class="result-count">${data.length} Dose ditemukan</div><section class="dose-list">${data.slice(0,limit).map(d=>doseCard(d,true)).join('')||'<div class="empty"><b>Tidak ada Dose yang cocok.</b><p>Coba kata atau kategori lain.</p></div>'}</section>${data.length>limit?'<button class="secondary load-more">Muat lebih banyak</button>':''}`, 'explore');const input=$('#explore-search'),select=$('#explore-category');input.oninput=()=>{write({exploreQuery:input.value,exploreLimit:24});clearTimeout(input.t);input.t=setTimeout(explore,180)};select.onchange=()=>{write({exploreCategory:select.value,exploreLimit:24});explore()};$('.load-more')?.addEventListener('click',()=>{write({exploreLimit:limit+24});explore()});if(state.focusSearch){input.focus();write({focusSearch:false})}}
async function library(){const token=++renderToken,[fav,down,custom,hist,lists]=await Promise.all(['favorites','downloads','customDoses','history','playlists'].map(store));if(token!==renderToken)return;const resolve=x=>x?.dose||repo.getById(x?.canonicalId||x?.doseId||x?.id)||repo.resolve?.(x?.title||x?.name),groups={fav,down,custom,hist:hist.sort((a,b)=>(b.at||0)-(a.at||0)),lists},active=state.libraryTab||'fav';page(`<header class="page-head"><div><p class="eyebrow">Tersimpan di perangkat</p><h1>Library</h1><p>Semua angka dan konten berasal dari data aktual Anda.</p></div>${icon('library')}</header><nav class="tabs">${[['fav','Favorit',fav.length],['down','Offline',down.length],['custom','My Dose',custom.length],['hist','Riwayat',hist.length],['lists','Playlist',lists.length]].map(([id,l,n])=>`<button data-lib="${id}" class="${active===id?'active':''}">${l}<small>${n}</small></button>`).join('')}</nav><section class="library-list">${libraryRows(active,groups[active],resolve)}</section>`, 'library');$$('[data-lib]').forEach(b=>b.onclick=()=>{write({libraryTab:b.dataset.lib});library()});bindCommon()}
function libraryRows(type,data,resolve){if(type==='lists')return data.map(x=>`<article class="library-row"><span class="row-icon">${icon('library')}</span><span><strong>${esc(x.name||'Playlist')}</strong><small>${(x.canonicalItems||x.items||[]).length} Dose</small></span></article>`).join('')||empty('Belum ada playlist');const rows=data.map(x=>{const d=resolve(x);if(!d)return'';return `<button class="library-row" data-dose="${d.id}">${image(artwork(d),`Artwork ${d.title}`)}<span><strong>${esc(d.title)}</strong><small>${type==='hist'?new Date(x.at||Date.now()).toLocaleString('id-ID'):type==='down'?'Tersedia offline':type==='custom'?'Dose buatan Anda':esc(d.categoryLabel||d.cat)}</small></span>${icon('chevron-right')}</button>`}).join('');return rows||empty(type==='fav'?'Belum ada favorit':type==='down'?'Belum ada Dose offline':type==='custom'?'Belum ada My Dose':'Riwayat masih kosong')}
function empty(title){return `<div class="empty"><b>${title}</b><p>Konten akan muncul otomatis setelah Anda menggunakan aplikasi.</p></div>`}
async function profile(){const token=++renderToken,[fav,down,custom,hist,lists]=await Promise.all(['favorites','downloads','customDoses','history','playlists'].map(store));if(token!==renderToken)return;const days=new Set(hist.filter(x=>x.at).map(x=>new Date(x.at).toISOString().slice(0,10))),minutes=hist.reduce((n,x)=>n+(+x.duration||+x.progressMinutes||0),0),prefs=state.preferences||{};page(`<header class="profile-hero"><img src="./assets/brand/meditasiku-logo-mark.png" alt="Logo MeditasiKu"><div><p class="eyebrow">Ruang personal</p><h1>${esc(state.displayName||'Sahabat Jiwa')}</h1><p>${[...(prefs.goals||[]),...(prefs.sounds||[])].join(' · ')||'Sanctuary belum dipersonalisasi'}</p></div></header><section class="stats"><article><b>${hist.length}</b><small>Sesi</small></article><article><b>${minutes?Math.round(minutes/6)/10:0}</b><small>Jam</small></article><article><b>${days.size}</b><small>Hari aktif</small></article></section><section class="profile-space"><p class="eyebrow">Koleksi aktual</p><h2>Jejak perjalanan</h2>${[['favorite','Favorit',fav.length],['download','Offline',down.length],['create','My Dose',custom.length],['library','Playlist',lists.length]].map(([i,l,n])=>`<div class="profile-row">${icon(i)}<span><strong>${l}</strong><small>${n} tersimpan</small></span></div>`).join('')}</section><button class="secondary settings">${icon('theme-mixer')} Pengaturan</button>`, 'profile');$('.settings').onclick=settings}
function create(){page(`<header class="page-head"><div><p class="eyebrow">Ruang kreasi</p><h1>Create Studio</h1><p>Buat recipe personal melalui Quick Create, Advanced Mixer, atau Structured Recipe.</p></div>${icon('create')}</header><section class="create-stage"><div class="create-orb">${icon('theme-mixer')}</div><h2>Bangun suasana Anda sendiri</h2><p>Recipe disimpan lokal dan tetap memakai batas volume serta peringatan keselamatan.</p><button class="primary open-create">Buka Create Studio</button></section>`, 'create');$('.open-create').onclick=()=>window.MeditasiKu.create()}
function settings(){const host=document.createElement('div');host.className='simple-modal';host.innerHTML=`<section><button class="modal-close" aria-label="Tutup">${icon('close')}</button><p class="eyebrow">Pengaturan lokal</p><h2>Sanctuary Anda</h2><label>Nama panggilan<input id="display-name" value="${esc(state.displayName||'')}"></label><button class="secondary redo">Ulangi onboarding</button><button class="secondary status">Status sistem</button><button class="primary save">Simpan</button></section>`;document.body.append(host);$('.modal-close',host).onclick=()=>host.remove();$('.redo',host).onclick=()=>{write({onboardingDone:false,onboardingStep:0});host.remove();route('onboarding')};$('.status',host).onclick=()=>window.MeditasiKu.status();$('.save',host).onclick=()=>{write({displayName:$('#display-name',host).value.trim()||'Sahabat Jiwa'});host.remove();profile()}}
function render(){if(!repo?.isReady?.())return void setTimeout(render,80);const r=state.route;if(r==='splash')return splash();if(r==='onboarding')return onboardingScreen();if(r==='home')return home();if(r==='explore')return explore();if(r==='library')return library();if(r==='profile')return profile();if(r==='create')return create();route('home')}
addEventListener('popstate',render);addEventListener('meditasiku:catalogue-ready',render);render();
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./meditasiku-sw.js').catch(()=>{}));
})();
